### ISSUE TITLE
Made a small OPML generator for webri.ng

### ISSUE THREAD

**Issue by voxpelli** [webri-ng/webri.ng#3]
Prompted by [a Mastodon post](https://mastodon.social/@voxpelli/110595182250086210) I created a little GitHub Action that daily pulls down the list for every webri.ng I have told it to pull ([currently only `cssjoy`](https://github.com/voxpelli/webring-opml/blob/e454970519d93eb6ebd763bcc3edac4058fa729a/.github/workflows/gh-pages.yml#L39)) and looks up all sites and whether they a feed and then creates an OPML file for every such specified webring and publishes it under its name like:

- http://webring-opml.voxpelli.com/cssjoy.opml

This is handy for one time imports but even more handy for tools that supports subscribing to an OPML list, like [eg. Inoreader does](http://blog.inoreader.com/2014/05/opml-subscriptions.html).

Here's how it looked when I subscribed to that OPML file in Inoreader:

![Skärmavbild 2023-06-23 kl  23 44 47](https://github.com/webri-ng/webri.ng/assets/34457/00a2e477-0fcb-4217-bc65-419741039ac6)

Thought I would create an issue to let you know 🙂 I thought about making a PR, but this is probably better as a scheduled standalone GitHub Action / GitHub Pages job than something that would live within this platform itself.

Edit: Forgot link to my repo: https://github.com/voxpelli/webring-opml

**Comment by ajxs** [comment]
Wow! This is really awesome! I'm always amazed at the incredible and original ideas that people have. I'm also so happy that people are finding new and interesting uses for the platform!
I'm very sorry for not seeing this until now! I never got an email notification about the issue. There's clearly something very wrong with my Github notifications, and I'm going to fix that immediately. If ever you need support in a hurry, and don't get a response on Github, please email me.
Currently I use 'Feedbro' in Firefox to track RSS feeds, which unfortunately doesn't support subscribing to an OPML feed. I think I'll check out some other feed readers!
